print(bool("abc"))
print(bool(345))
print(bool(345.000001))
print(bool(["a", "b", "c"]))
print(bool(False))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool([]))
print(bool({}))
